PORTNAME=	retry
DISTVERSION=	1.0.5
CATEGORIES=	zomo
MASTER_SITES=	GH
LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	minfrin
GH_TAGNAME=	4a74786
MAINTAINER=	jon@zikomo.xyz

COMMENT=	Retry a command until the command succeeds

USES+=		autoreconf
HAS_CONFIGURE=	1
BUILD_DEPENDS=	txt2man:textproc/txt2man

.include <bsd.port.mk>

# vi:ts=8
